### PR TITLE
Bump all dependencies

### PR DESCRIPTION
**Pull request by jkroepke**
Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>

This should resolve some vulnerability alerts:

```
jiralert % trivy filesystem .

go.mod (gomod)

Total: 60 (UNKNOWN: 26, LOW: 1, MEDIUM: 7, HIGH: 24, CRITICAL: 2)
```

### CODE REVIEW

**Comment by bwplotka** [comment]
Thanks, but sounds like the CI changes you added have some issues to build our code.

**Comment by jkroepke** [comment]
It works locally now:

```
% make
>> checking code style
>> checking license header
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /Users/jok/go/bin/golangci-lint run  ./...
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
>> running check for unused/missing packages in go.mod
GO111MODULE=on go mod tidy
>> building binaries
GO111MODULE=on /Users/jok/go/bin/promu build --prefix /Users/jok/Downloads/jiralert 
 >   jiralert
>> running all tests
GO111MODULE=on go test   ./...
?       github.com/prometheus-community/jiralert/cmd/jiralert   [no test files]
?       github.com/prometheus-community/jiralert/pkg/alertmanager       [no test files]
ok      github.com/prometheus-community/jiralert/pkg/config     0.314s
ok      github.com/prometheus-community/jiralert/pkg/notify     0.410s
?       github.com/prometheus-community/jiralert/pkg/template   [no test files]
jok@CDT-MB-20200178 jiralert % make common-lint
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /Users/jok/go/bin/golangci-lint run  ./...
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
jok@CDT-MB-20200178 jiralert % docker build -t a .            
[+] Building 38.6s (12/12) FINISHED                                                                                                                                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                               0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                    0.0s
 => [internal] load metadata for quay.io/prometheus/busybox-linux-amd64:latest                                                                                                                                                                                                                                     0.6s
 => [internal] load metadata for docker.io/library/golang:1.19                                                                                                                                                                                                                                                     1.6s
 => [builder 1/4] FROM docker.io/library/golang:1.19@sha256:25de7b6b28219279a409961158c547aadd0960cf2dcbc533780224afa1157fd4                                                                                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                  0.2s
 => => transferring context: 15.29MB                                                                                                                                                                                                                                                                               0.2s
 => CACHED [stage-1 1/2] FROM quay.io/prometheus/busybox-linux-amd64:latest@sha256:c9f983fc55b0b74723a69c31688cca7d5a2e5b2af7c954780f29a331817982f3                                                                                                                                                                0.0s
 => CACHED [builder 2/4] WORKDIR /go/src/github.com/prometheus-community/jiralert                                                                                                                                                                                                                                  0.0s
 => [builder 3/4] COPY . /go/src/github.com/prometheus-community/jiralert                                                                                                                                                                                                                                          0.1s
 => [builder 4/4] RUN GO111MODULE=on GOBIN=/tmp/bin make                                                                                                                                                                                                                                                          36.6s
 => [stage-1 2/2] COPY --from=builder /go/src/github.com/prometheus-community/jiralert/jiralert /bin/jiralert                                                                                                                                                                                                      0.0s 
 => exporting to image                                                                                                                                                                                                                                                                                             0.0s 
 => => exporting layers                                                                                                                                                                                                                                                                                            0.0s 
 => => writing image sha256:54b94b975d034b71309edd2b1a11154f4573046f0b59ce6f3c8215123da645fd                                                                                                                                                                                                                       0.0s
 => => naming to docker.io/library/a                                                                                                                                                                                                                                                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
jok@CDT-MB-20200178 jiralert % trivy image docker.io/library/a
2022-10-20T13:23:46.711+0200    INFO    Vulnerability scanning is enabled
2022-10-20T13:23:46.711+0200    INFO    Secret scanning is enabled
2022-10-20T13:23:46.711+0200    INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-10-20T13:23:46.711+0200    INFO    Please see also https://aquasecurity.github.io/trivy/v0.32/docs/secret/scanning/#recommendation for faster secret detection
2022-10-20T13:23:47.077+0200    INFO    Number of language-specific files: 1
2022-10-20T13:23:47.077+0200    INFO    Detecting gobinary vulnerabilities...

```

**Review by bwplotka — APPROVED** [review]
Lgtm, thanks!

**Comment by jkroepke** [comment]
@bwplotka are you able to merge and release this? Thanks

**Comment by jkroepke** [comment]
@bwplotka It is possible to do a release including this PR?

**Pull request merged**
