### PR TITLE
Update Go dependencies

### PR DESCRIPTION
**Pull request by priteau**
This includes go-jira v1.15.0 supporting Personal Access Tokens (PATs).

### CODE REVIEW

**Review by mrueg — APPROVED** [review]

**Comment by mrueg** [comment]
@priteau looks like the linting/tests failed, would you mind taking a look? 

https://github.com/andygrunwald/go-jira/releases/tag/v1.15.1 was released with a couple of additional fixes.

**Comment by priteau** [comment]
There was a deprecation in `go-kit/kit`, but I am still hitting `errcheck` issues. Do you know what should go into `.errcheck_excludes.txt` to avoid them?

**Comment by mrueg** [comment]
Something with the go-jira packaging might have changed. I believe the go-jira imports need to be updated and be used like this now:
`jira "github.com/andygrunwald/go-jira"`

**Comment by mrueg** [comment]
Do you want to raise the golang version in these files and see if that fixes it? https://github.com/prometheus-community/jiralert/blob/master/.github/workflows/build-docker.yaml#L13 
https://github.com/prometheus-community/jiralert/blob/master/.github/workflows/test.yaml#L15
https://github.com/prometheus-community/jiralert/blob/master/Dockerfile#L1
https://github.com/prometheus-community/jiralert/blob/master/go.mod#L3

**Comment by priteau** [comment]
I am not sure it makes sense to bump Go version requirements just for a linting issue. `go-jira` itself still claims to support 1.14. I am trying to run tests with 1.15 now, then I may try adding `//nolint` comments.

**Comment by rporres** [comment]
This will certainly conflict with the PR I've sent adding support for PAT in jiralert 😅  https://github.com/prometheus-community/jiralert/pull/110

**Comment by priteau** [comment]
Closing since go-jira was updated to v1.15.1 in #110.

**Pull request closed without merging**
